### ISSUE TITLE
Speed improvement

### ISSUE THREAD

**Issue by nickshanks** [ChristianRiesen/base32#10]
Line 89:
https://github.com/ChristianRiesen/base32/blob/master/src/Base32.php#L89

Currently:
$base32String .= substr(self::$alphabet, $char, 1);

Would be faster as:
$base32String .= self::$alphabet[$char];

(see http://php.net/manual/en/language.types.string.php#language.types.string.substr)

**Comment by ChristianRiesen** [comment]
Thanks. I added it on your input and then saw the merge request later :) Merged it anyways and tagged new version.

Thanks for the input!
