### ISSUE TITLE
Drop support for ancient PHP versions

### ISSUE THREAD

**Issue by reedy** [ChristianRiesen/base32#17]
https://www.php.net/supported-versions.php

I think it's probably time to drop support for < 7.0, and maybe go upto 7.2.

It's also probably worth dropping support for HHVM too, as that's diverged into its own thing - https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Comment by reedy** [comment]
https://github.com/reedy/base32/tree/bumpversions is starting to do that...

**Comment by ChristianRiesen** [comment]
Support is limited to 7.2 in #23 
HHVM is gone too, all is switched to github actions now.
