### ISSUE TITLE
satooshi/php-coveralls is abandoned

### ISSUE THREAD

**Issue by reedy** [ChristianRiesen/base32#21]
https://packagist.org/packages/satooshi/php-coveralls says to use https://packagist.org/packages/php-coveralls/php-coveralls instead

**Comment by ChristianRiesen** [comment]
I decided to just kill it. If you would like to make a PR for adding some coverage thing that works with github actions, please do. IMHO the code is well tested the way it is now and should do fine. And of course you are always welcome to add more tests :)

**Comment by reedy** [comment]
In theory, it's trivially doable with phpunit...
