### ISSUE TITLE
BUG - Unpacking signed chars, not unsigned chars

### ISSUE THREAD

**Issue by samuelwilliams** [ChristianRiesen/base32#26]
https://github.com/ChristianRiesen/base32/blob/045f1676849bbb67c7c06d8f7ee91657d911fa41/src/Base32.php#L97

When unpacking the string, the `$format` used is `'c*'` (signed char) - this is the wrong format, it leads to bytes larger than `0x7f` being interpreted as negative integers. The correct format is `'C*'` (unsigned char).

The tests cannot pick this up because they are limited to the ASCII space (`0x00 - 0x7F`).

**Comment by samuelwilliams** [comment]
P.S. I am very sorry

**Comment by ChristianRiesen** [comment]
No problem, happens to the best of us. Now it's better off with more tests. This bug actually screwd up an application this is used in that I work on, so I would have noticed it latest today :)
